import { Rajdhani } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import CartProvider from "@/components/CartProvider";
import { Toaster } from "@/components/ui/toaster";

const rajdhani1 = Rajdhani({ subsets: ["latin"] , weight:['300','400','500','600','700'], variable: '--font-rajdhani', });

export const metadata = {
  title: "Bikezz",
  description: "Generated by create next app",
  icons:{
    icon:['/favicon.ico?v=4'],
    apple:['/apple-touch-icon?v=4'],
    shortcut:['apple-touch-icon.png']
  },
  manifest: '/site.webmanifest'
 
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rajdhani1.className}>
        <CartProvider>
        <Header />
        {children}
        <Toaster/>
        <Footer/>
        </CartProvider>
        {/* <div className="h-[2000px]"></div> */}
        </body>
    </html>
  );
}
